<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opsi Acting Sales Head b</name>
   <tag></tag>
   <elementGuidId>43e90bfa-ea08-4c26-bf3d-15f52b755532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='posisi-kerja-option-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#posisi-kerja-option-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d6e60133-51fe-42a2-8677-7300bac4a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8e35d54e-2d9a-4a27-82cb-6c9710fc6b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>aff09b0b-2c18-42fb-9f04-f2fdde6b1810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posisi-kerja-option-5</value>
      <webElementGuid>a258834a-5935-488e-9ae7-030d7f705790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>aab343c4-8f8a-4f91-8deb-03e00358946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69a0ebe7-8fe0-495f-a141-f830b020d2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3340456b-86d8-4872-a537-b1a3bdc686a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>aacad8e3-f67a-4774-8468-1c1b08709213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acting Sales Head b</value>
      <webElementGuid>34fc0237-7f4d-4dc0-98cd-17a8df3738a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;posisi-kerja-option-5&quot;)</value>
      <webElementGuid>c11e8512-ffc1-4c1e-9e8b-3efd9cd8552f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='posisi-kerja-option-5']</value>
      <webElementGuid>7fb981c3-71e4-4cb4-adca-8b309a45386f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='posisi-kerja-listbox']/li[6]</value>
      <webElementGuid>a135ae7e-9c83-4068-8183-6980c463e28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abv'])[1]/following::li[1]</value>
      <webElementGuid>1a66242a-20ce-4449-9036-715995e21140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aaaa'])[1]/following::li[2]</value>
      <webElementGuid>cf9b0c79-6663-4027-bb87-9de96fa0f4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin 1'])[1]/preceding::li[1]</value>
      <webElementGuid>707106b7-be6c-4e23-9174-b621b10203c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin 1'])[2]/preceding::li[2]</value>
      <webElementGuid>4f7b7727-bb74-4879-9b76-05be50a5b954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acting Sales Head b']/parent::*</value>
      <webElementGuid>f201b23a-69b6-4402-8c69-8b4e691fcd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]</value>
      <webElementGuid>eaa91af7-e5b4-4cf9-845f-c86a03f1ffa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'posisi-kerja-option-5' and (text() = 'Acting Sales Head b' or . = 'Acting Sales Head b')]</value>
      <webElementGuid>3e1c9917-9d4b-4282-b6d0-56076b4b39f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
