<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opsi Admin Warung Bukalapak</name>
   <tag></tag>
   <elementGuidId>a7e24922-ee15-4f21-949e-f0a195cceea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='jadwal-kerja-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jadwal-kerja-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>22ca0e93-7376-4682-b848-3cf4010f8e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d091041b-7cfa-4957-8b1b-be610359d9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6d3d9e4b-48d7-42b7-ae45-2c5f9dbb23cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jadwal-kerja-option-6</value>
      <webElementGuid>e7dc805b-42a3-4190-b5da-695c546aac6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>99615441-7a71-4119-8a57-55cab1ba92a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c382a2d-1913-4766-8003-6050ec1e21da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2f9fa13b-086f-4b17-87c5-a68f01b8cf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>94e84a6e-75f4-4db8-95ba-ec6d5bfd9b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Warung Bukalapak</value>
      <webElementGuid>06c000c1-ae72-4372-bfd8-063e7cc59b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jadwal-kerja-option-6&quot;)</value>
      <webElementGuid>b4f83383-14c1-4e2e-a3b1-575850bac410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='jadwal-kerja-option-6']</value>
      <webElementGuid>e71becfd-4000-4a10-8451-5abc58b13f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jadwal-kerja-listbox']/li[7]</value>
      <webElementGuid>25c455f7-6af2-4052-8503-96814e97070e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adad'])[1]/following::li[1]</value>
      <webElementGuid>a4be9f00-b516-41e7-9c2a-bc9a9e668af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a2testing'])[2]/following::li[2]</value>
      <webElementGuid>73b8a600-4ed2-4bec-b0d6-9d557b28a731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Warung Bukalapak - 1'])[1]/preceding::li[1]</value>
      <webElementGuid>a9ba675b-179d-48be-a5b5-1c41fd22dd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank KB Bukopin'])[1]/preceding::li[2]</value>
      <webElementGuid>405f7c11-9d50-4a62-aefb-09076415a9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Warung Bukalapak']/parent::*</value>
      <webElementGuid>7d50da41-f2eb-4ab5-bded-afc24050daae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>ca1968db-8a6f-4c57-81ef-a1d435039d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'jadwal-kerja-option-6' and (text() = 'Admin Warung Bukalapak' or . = 'Admin Warung Bukalapak')]</value>
      <webElementGuid>2ede031e-6091-4755-b267-4afb724900bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
