<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opsi staff 2</name>
   <tag></tag>
   <elementGuidId>3dd833b2-ca61-4805-a405-07f86d87755b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='free-solo-with-text-demo-option-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#free-solo-with-text-demo-option-3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;free-solo-with-text-demo-option-3&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cba6e42e-8e82-4a7d-b017-5c943d5edd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f36178a0-5c86-41fc-82c7-c263a8de2d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c2fa2d2e-2150-447a-851e-01c1b6c037a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>free-solo-with-text-demo-option-3</value>
      <webElementGuid>fe30f5d1-ddcb-4226-915e-d4a436669f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2717626f-534a-4568-827f-cc4593da22ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2738c741-42e7-4ef4-9965-5b1cbbbedeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>003f3cc9-54f3-4a5a-8162-7ef62520ef5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>b0083901-bb8e-4583-b25f-2ee968254bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>staff 2</value>
      <webElementGuid>2e405ac1-56eb-4200-a995-f9d55f8db2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;free-solo-with-text-demo-option-3&quot;)</value>
      <webElementGuid>a2a69ef0-d7ff-47a9-9bf3-06214207f40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='free-solo-with-text-demo-option-3']</value>
      <webElementGuid>6ee70380-bc6d-4a52-8898-5f09cb706ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='free-solo-with-text-demo-listbox']/li[4]</value>
      <webElementGuid>4eee27cc-2a11-44d9-8cce-874d17545a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Jabatan'])[1]/following::li[1]</value>
      <webElementGuid>13eab878-f4a3-4508-8993-7c6638002cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TC-A-001'])[2]/following::li[2]</value>
      <webElementGuid>d2217408-f2f0-4bd4-b514-a6c502b20953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AAAAAAAa'])[1]/preceding::li[1]</value>
      <webElementGuid>5b5fb345-7123-4dca-857c-eee43f959c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Sales Manager'])[1]/preceding::li[2]</value>
      <webElementGuid>9d3b8346-dc50-4b8f-b8b4-c6d3b6c765cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='staff 2']/parent::*</value>
      <webElementGuid>5bd862d0-65ed-4852-a60f-3da99810b6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[4]</value>
      <webElementGuid>fba4692a-5b45-4392-9c34-0688c5f6e834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'free-solo-with-text-demo-option-3' and (text() = 'staff 2' or . = 'staff 2')]</value>
      <webElementGuid>7806be5c-ac1a-4fce-8a86-93743d9716dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
