<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opsi BCA Life</name>
   <tag></tag>
   <elementGuidId>5a1fe2f1-3755-4497-b31a-3d6faa8bcb7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='free-solo-with-text-demo-option-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#free-solo-with-text-demo-option-16</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;free-solo-with-text-demo-option-16&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>64e1c809-3f60-490a-a551-6873a34eaefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>79ef31d1-c46f-4eeb-95ef-f027cc1e08e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8b8f2e8f-8b1a-431f-92ef-d554c779ddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>free-solo-with-text-demo-option-16</value>
      <webElementGuid>df8965a2-aa36-4091-a1c8-65166b208e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c04f53d4-98e5-4ec8-84d0-cf844b47bff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8ab1edb-03ef-4535-b328-5f7b3701aa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>166d763e-5163-47c7-9b68-64d226118358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>2fdfa73e-aafc-4222-b6ae-83fef4ee0b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCA Life</value>
      <webElementGuid>31a4675e-15a3-489d-8e6f-6145570c1e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;free-solo-with-text-demo-option-16&quot;)</value>
      <webElementGuid>f21ddc0f-7688-42d0-98e2-d4ab251af04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='free-solo-with-text-demo-option-16']</value>
      <webElementGuid>84991f68-a8ca-44b5-93b1-f8c9cf307f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='free-solo-with-text-demo-listbox']/li[17]</value>
      <webElementGuid>0afdb8f3-deee-4641-95e4-7e89aac6973c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='baru'])[1]/following::li[1]</value>
      <webElementGuid>a99c2960-8ce8-4a75-9d50-e27247f484ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Neo Commerce'])[1]/following::li[2]</value>
      <webElementGuid>55271474-fa95-4b2e-9d7a-2fd7d7ec7b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA Syariah'])[1]/preceding::li[1]</value>
      <webElementGuid>435e2681-9053-4085-b323-2331e37c837d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukalapak AE'])[1]/preceding::li[2]</value>
      <webElementGuid>73c393b4-cbf7-4237-b8e1-94dd199ef338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BCA Life']/parent::*</value>
      <webElementGuid>6eec5bbe-22cc-4211-a9c4-72e76ff27665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[17]</value>
      <webElementGuid>8b020dd2-faab-4218-8abf-ef319577d751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'free-solo-with-text-demo-option-16' and (text() = 'BCA Life' or . = 'BCA Life')]</value>
      <webElementGuid>7b64334f-51dc-46b3-95e6-d619f8e4ec0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
