<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter Posisi Kerja</name>
   <tag></tag>
   <elementGuidId>afc3d1ca-0b15-4e22-abc2-a85c3b5d3288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-job_position_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-component-select-job_position_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>014ddeb8-76bf-41cc-937a-e37538dfdae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8cf65cc-1ab8-481a-9614-b8f4b0da7dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>0dbceb94-0aeb-4bec-990d-aeedfd6da1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c0ae3ab-531d-427a-b365-f00d3e2f6849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>24d54982-7ddf-49f3-970f-7c2cd9e442a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-component-select-job_position_id</value>
      <webElementGuid>d3f3e59f-5224-43d2-82ba-3eba21e6525b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-component-select-job_position_id</value>
      <webElementGuid>80b7637b-2df1-44ec-9419-fa582a5c5013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-1cbz1az</value>
      <webElementGuid>4ada7e84-c01f-41cd-baeb-60ccf8575fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mui-51</value>
      <webElementGuid>1f6c7ff1-b12d-4ece-826c-de91679cf8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>31cdb84e-55e8-4aaf-abf5-8792115f6029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-component-select-job_position_id&quot;)</value>
      <webElementGuid>edef7a24-06ba-4c32-be96-0795d1dd9cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-component-select-job_position_id']</value>
      <webElementGuid>daeae737-986f-4774-b02e-6242b40b076d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi Kerja'])[2]/following::div[2]</value>
      <webElementGuid>bcf3efc7-4b6c-481d-81ed-c0725fc2f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi Kerja'])[1]/following::div[3]</value>
      <webElementGuid>1e8600a7-9e6e-402b-ac3d-2a432d679de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi Kerja'])[3]/preceding::div[1]</value>
      <webElementGuid>3fce5063-fd26-4d5d-aab7-c1ce561d58c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>e648e696-c5d0-4a13-9bc8-31a76984889c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-component-select-job_position_id' and (text() = '​' or . = '​')]</value>
      <webElementGuid>23d22623-bee7-4fff-91bb-0a84c354aed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
