<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Admin Recruitment</name>
   <tag></tag>
   <elementGuidId>e80c97e1-838e-4941-adc1-ea562e9d5ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='posisi-kerja-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#posisi-kerja-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a6329969-9e25-4e50-98ab-6598e3adcba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f08ef9b0-7093-463a-ae78-e0bdee7e8bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ced4a6b7-60c6-4875-8d79-fab24edf4a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posisi-kerja-option-0</value>
      <webElementGuid>1f1eeefc-46e4-46d9-a9fa-5b38b1a872bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d1ab590-2f67-4de7-a2d4-bf9146ad90d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9755bb99-4e09-4468-a4a0-4f9880bec463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df99ea67-938c-49c5-9223-ed99f1550d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>30e4791a-d6c5-4560-b482-45a9bdadc70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Recruitment</value>
      <webElementGuid>657854df-1bad-4b77-8542-7c81ab49d26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;posisi-kerja-option-0&quot;)</value>
      <webElementGuid>78d464fe-5dbe-428c-a849-e96b66d7d01f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='posisi-kerja-option-0']</value>
      <webElementGuid>cc4a5403-a07c-41ab-933e-73bcd341fa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='posisi-kerja-listbox']/li</value>
      <webElementGuid>2ff2b84b-34ce-43f6-90a6-092394721af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>96ebca16-49a0-4eba-9dde-cea95b97cd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Recruitment']/parent::*</value>
      <webElementGuid>0fc9aecd-3596-4e97-88db-fecd36fa6c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>8432454a-c081-4a5b-85b5-8fff2585bcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'posisi-kerja-option-0' and (text() = 'Admin Recruitment' or . = 'Admin Recruitment')]</value>
      <webElementGuid>6a4ee119-dfad-4988-99b5-b6d70e1738d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
