<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Admin Warung Bukalapak</name>
   <tag></tag>
   <elementGuidId>718cf6ef-1237-4fd3-b172-979d15311633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='jadwal-kerja-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jadwal-kerja-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>701a533e-11bd-4114-a90c-a151be43ef41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c6102771-4ae8-4cb4-8f5c-f5d4d11a346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8491c60e-e837-4a21-b201-5107ea196779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jadwal-kerja-option-0</value>
      <webElementGuid>88a3af8d-bd0a-4945-8c44-4d9e36bd8c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c4ac6a5-b8b2-4286-b58c-665f84ad74e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14c4839f-a6b3-4cd8-8a8e-07d0996a7d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d41b6f6-13b8-4bad-8ec3-c7ed6d9ce032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>9daa2eb3-7c10-47e1-859e-2095a366b483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin Warung Bukalapak</value>
      <webElementGuid>6bc66a17-d8ba-4ef0-b9b6-44cb5bd68343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jadwal-kerja-option-0&quot;)</value>
      <webElementGuid>3e6a4e93-3b30-48b0-b104-576ea39ae9f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='jadwal-kerja-option-0']</value>
      <webElementGuid>d11e6ddb-5849-494c-9499-558ad908ffc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jadwal-kerja-listbox']/li[3]</value>
      <webElementGuid>1b83d177-973e-4868-a1bf-5d25eadab4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a2testing'])[2]/following::li[1]</value>
      <webElementGuid>8a889b69-5668-42ee-b14b-0f5e90894807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a2testing'])[1]/following::li[2]</value>
      <webElementGuid>8d5a2e02-01b3-4bca-b70b-eae98976ce17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Warung Bukalapak - 1'])[1]/preceding::li[1]</value>
      <webElementGuid>c24b7e91-8ec2-4c87-8638-73fc36be0477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kerja'])[1]/preceding::li[2]</value>
      <webElementGuid>6ff92afe-61ea-4bcb-8e33-fb14a5f61f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Warung Bukalapak']/parent::*</value>
      <webElementGuid>df35022a-09d2-4ec7-b966-8b6bb9bcfeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[3]</value>
      <webElementGuid>4e98a7f3-283a-4cf6-b116-c686925c128f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'jadwal-kerja-option-0' and (text() = 'Admin Warung Bukalapak' or . = 'Admin Warung Bukalapak')]</value>
      <webElementGuid>15113dd0-2aad-4ac4-9615-b4ad73527a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
