<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DIKA 1</name>
   <tag></tag>
   <elementGuidId>ee1345f7-469e-4e66-bbdb-17659445b91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'DIKA 1' or . = 'DIKA 1')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='lokasi-kerja-option-7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lokasi-kerja-option-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b6354753-5a75-49d1-a261-c74fdd4a89e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5973f1b4-871b-4b07-8080-fbb34f807c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fc44ee3e-bb12-401a-911b-eb6f840d1f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lokasi-kerja-option-7</value>
      <webElementGuid>34c343a0-07a3-460d-8782-cfb554d0e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>1fe38145-290e-43de-a6f5-4d6e03662a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f34fcc56-85b0-4b8d-a8f9-2078c8796ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>466d71b0-b330-4626-b4f6-9492a4fbeb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>c243ea1d-a7b8-4f64-b400-15de2048a92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIKA 1</value>
      <webElementGuid>7921fee3-9201-4ed5-a161-9fd6abe6e5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lokasi-kerja-option-7&quot;)</value>
      <webElementGuid>56972af6-eb27-44b3-b6a9-3b496d4643d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='lokasi-kerja-option-7']</value>
      <webElementGuid>5f72a05a-862e-467a-884e-f0df4d5fd3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='lokasi-kerja-listbox']/li[8]</value>
      <webElementGuid>11910885-2ec6-4bdf-9b57-5bb95522841f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='data2new'])[1]/following::li[1]</value>
      <webElementGuid>a4e6d704-4bbd-4601-a908-314999abbbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Damora'])[1]/following::li[2]</value>
      <webElementGuid>c10a81d3-a636-4b0c-9c87-cc8af83cef3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIKA 2'])[1]/preceding::li[1]</value>
      <webElementGuid>4ad0f437-e160-4d52-a65b-1fb8f6e0be04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIKA Balikpapan'])[1]/preceding::li[2]</value>
      <webElementGuid>18c9c224-9f93-4717-aa48-87102fdce101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIKA 1']/parent::*</value>
      <webElementGuid>74274586-134d-49f5-941e-7a48b90717d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>c4ae5c33-3b87-4b0d-898e-79b8d94ded7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'lokasi-kerja-option-7' and (text() = 'DIKA 1' or . = 'DIKA 1')]</value>
      <webElementGuid>d3003dc6-c449-43ef-b575-15d96fb18cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
