<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nama - Air Asia</name>
   <tag></tag>
   <elementGuidId>53ef61a4-9f18-4802-9ba1-22abc2a1b6d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Nama - Air Asia' or . = 'Nama - Air Asia')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='atasan-v3-option-7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#atasan-v3-option-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b078b9eb-52c8-4e9b-922d-8a6207eeb064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ab292b96-a401-4b47-8c48-39ecc0085321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b1dbd102-35d3-4485-aa75-d1c90757951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atasan-v3-option-7</value>
      <webElementGuid>12774dd8-4c7f-4172-a62c-b35f0a27d6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>7519b2f0-7d5d-4767-be5e-e8db94efcad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cbdcdbb-3cff-4970-987f-d8886167fc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b6d0f4b-9b19-4bec-9fc2-994c43a1fe63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>bcf65ff1-1fb4-4fe4-a358-a9dc137f254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama - Air Asia</value>
      <webElementGuid>24cf85f4-5fe6-449e-aa58-891da8a2990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atasan-v3-option-7&quot;)</value>
      <webElementGuid>a2a874cd-33ef-45ae-9253-ba3b76d50021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='atasan-v3-option-7']</value>
      <webElementGuid>649fb666-ba42-4b88-8cc2-5cdc45560770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='atasan-v3-listbox']/li[8]</value>
      <webElementGuid>5c5a14b3-caba-4ea2-b6df-df8a53857032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reid Reilly - Air Asia'])[1]/following::li[1]</value>
      <webElementGuid>af7ea98b-6bbb-4174-8c0f-f1ad96e9bfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allan Kshlerin - Air Asia'])[1]/following::li[2]</value>
      <webElementGuid>d834964c-70bf-47af-9317-78be14a50904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nata - BCA Biro Keuangan dan SDM'])[1]/preceding::li[1]</value>
      <webElementGuid>29e696d1-7293-495f-b163-4e7b0b7e21ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nata - BCA Biro Keuangan dan SDM'])[2]/preceding::li[2]</value>
      <webElementGuid>b0190d26-0af3-4900-8339-de17f2cae8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama - Air Asia']/parent::*</value>
      <webElementGuid>6a45792c-d16f-4f51-9e1f-d8d6d2b842e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>7a45d707-4299-4e2e-a7eb-d2af14374c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'atasan-v3-option-7' and (text() = 'Nama - Air Asia' or . = 'Nama - Air Asia')]</value>
      <webElementGuid>5e31fa54-de62-4394-af28-74b4bbc729a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
