<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PilihanPosisiKerja</name>
   <tag></tag>
   <elementGuidId>e80c97e1-838e-4941-adc1-ea562e9d5ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#posisi-kerja-option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'posisi-kerja-option-0' and (text() = 'yusu' or . = 'yusu')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='posisi-kerja-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>72c815b3-a644-4e91-8fd9-913e4a5d3173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1444e4ec-429c-4d57-9a3e-1319b173bc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>625236b0-4891-487b-bb75-7ed36c7b7636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posisi-kerja-option-0</value>
      <webElementGuid>dd41d55b-64f9-4bf4-9e3d-6e76af1da276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>930ac357-2df1-4d36-bb25-bbb8dbd6a42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cff289b5-2bfa-465d-aa30-04345611db4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18bd6bbe-5ce9-4789-ba0b-f9908a7b81f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>46220e71-d688-4852-b1d6-baab6c2cd362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>yusu</value>
      <webElementGuid>2b520e5c-7e9b-43e9-9067-c5b8a4946eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;posisi-kerja-option-0&quot;)</value>
      <webElementGuid>04f72a2f-9e1c-4595-b27e-69923b27c350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='posisi-kerja-option-0']</value>
      <webElementGuid>8063d152-a296-4b37-b6d3-6d6b2aa23771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='posisi-kerja-listbox']/li</value>
      <webElementGuid>09c32c6e-2eaa-4cf7-9933-fa7758142ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>11ee1767-48cc-4eb6-a99a-00565fb05f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Recruitment']/parent::*</value>
      <webElementGuid>90821a06-c2a1-4552-91bb-617534a1a975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>5db7eab3-c39a-4788-8edd-7965151c916d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'posisi-kerja-option-0' and (text() = 'Admin Recruitment' or . = 'Admin Recruitment')]</value>
      <webElementGuid>f97da16e-64ea-47fa-bd63-0f6118121a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
